# Generated by Django 3.0.3 on 2020-02-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_quiz_times_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_length',
            field=models.CharField(default='', max_length=100),
        ),
    ]
