# Generated by Django 3.0.3 on 2020-03-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='text',
            name='video_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
