# Generated by Django 3.0.3 on 2020-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20200319_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='text',
            name='video_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
